ServerName "SakovichServer"
ServerType standalone
UseIPv6 off
DefaultRoot ~
Port 21
Umask 022

<Anonymous /home/public>
  User ftp
  Group nogroup
  UserAlias anonymous ftp
  RequireValidShell off
  <Directory /home/public>
    <Limit WRITE>
      DenyAll
    </Limit>
  </Directory>
</Anonymous>
